In [ ]:
a = [i for i in range(10)]  # Create a list of integers from 0 to 9
print(a)

import numpy as np  # Import the NumPy library

# Creating NumPy arrays:
# np.array: Converts a list or tuple into a NumPy array
# np.zeros: Creates an array filled with zeros
# np.ones: Creates an array filled with ones
# np.linspace(start, stop, num): Creates an array with evenly spaced numbers between start and stop

# Properties of NumPy arrays:
# arr.shape: Returns the shape (dimensions) of the array
# arr.size: Returns the total number of elements in the array
# arr.ndim: Returns the number of dimensions of the array

# Accessing array elements:
# Use square brackets to index elements: e.g., A[1] for the second element
# Slicing arrays: e.g., A[1:5] gets elements from index 1 to 4 (not including 5)
# Advanced slicing:
#    - A[::]: Gets all elements
#    - A[::-1]: Reverses the array
# For multidimensional arrays:
#    - A[row, column]: Access specific elements
#    - A[:5, 5:]: Slices rows and columns

# Reshaping arrays:
# arr.reshape(new_shape): Reshapes the array into the specified shape

# Matrix operations:
# np.dot(A, B): Performs dot product of two arrays
# A @ B: Another way to perform matrix multiplication
# np.matmul(A, B): Multiplies matrices (does not handle 1D vectors the same as dot product)

# Example usage:
a = np.array((1, 2, 3))  # Create a 1D NumPy array
b = np.array((1))        # Create a scalar array
print(a + b)             # Adds scalar b to each element of array a


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4]


4.1 Problem - 1:
 Array Creation:

In [ ]:
import numpy as np

a=np.empty((2,2))#Initialize an empty array with size 2X2.
print("Empty_array:","\n",a)

one_array=np.ones((4,2))#one array with size 4X2
print("Ones array: ","\n", one_array)
print("Np.full: ",np.full(4,2))
#The first argument should be an array-like object
print("Zeros_like: ","\n",np.zeros_like(a))  # Use 'a' as a template to create a zeros array
print("Ones_like: ","\n",np.ones_like(one_array)) # Use 'one_array' as a template to create a ones array
new_list=[1,2,3,4]#converting to a numpy array
print("Np.array:",np.array(new_list))

Empty_array: 
 [[4.91100909e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
Ones array:  
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Np.full:  [2 2 2 2]
Zeros_like:  
 [[0. 0.]
 [0. 0.]]
Ones_like:  
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Np.array: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [2]:
import numpy as np

print("Ranging from 10 to 49: ","\n",np.arange(10,49))# array ranging from 10 to 49

array=np.array([[0,1,2],[3,4,5],[6,7,8]])
reshaped_array=array.reshape(9,1)
print("Reshaped_array: \n",reshaped_array)

a=np.eye(3,3)
print("Identity matrix: \n", a)

random_array=np.random.random(30)
print("Random_array: \n",random_array)
mean_value=random_array.mean()
print("MeanValue: \n", mean_value)

mini_max=np.random.rand(10,10)
print("Minimum: \n",np.min(mini_max))
print("Maximum: \n",np.max(mini_max))

#Instead of np.zeros_like, use np.zeros to specify the size
zero_size=np.zeros(10) #Creating a 1-D array of 10 zeros
#If you need a 2x2 array: zero_size = np.zeros((2, 2))
#If you need a multi-dimensional array you should specify the dimensions as a tuple.


remove_element = np.zeros(10)
remove_element[4]=1
print("Removing 5th element: ", remove_element)

arr=[1,2,0,0,4,0]
print("ReversedArray: \n",arr[::-1])#it prints the reverse
print("OrginalArray: \n",arr[::])#it prints the orginal

# Define the dimensions of the array
rows = 5
cols = 6

# Create an array filled with 1s
bordered_array = np.ones((rows, cols))

# Set the inner elements to 0 using slicing
bordered_array[1:-1, 1:-1] = 0

# Print the resulting array
print("BoarderedArray: \n",bordered_array)

# Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill odd rows with 1s at even columns
checkerboard[::2, 1::2] = 1  # Fill even rows with 1s at odd columns

print("Checkerboard Pattern:")
print(checkerboard)

Ranging from 10 to 49:  
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
Reshaped_array: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random_array: 
 [0.52041335 0.22900854 0.56449476 0.62902148 0.26270469 0.54248543
 0.6827356  0.48256777 0.90762659 0.45200838 0.92692584 0.60407586
 0.10716392 0.95835628 0.10117872 0.87905761 0.77733955 0.98785077
 0.01054664 0.0103756  0.26748312 0.47338762 0.79308162 0.84264426
 0.54070995 0.92291915 0.22435766 0.77417873 0.99859704 0.36429305]
MeanValue: 
 0.5612529858150827
Minimum: 
 0.02193840117281831
Maximum: 
 0.9963032955298572
Removing 5th element:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
ReversedArray: 
 [0, 4, 0, 0, 2, 1]
OrginalArray: 
 [1, 2, 0, 0, 4, 0]
BoarderedArray: 
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
Checkerboard Pattern:
[[0 1 0 1 0 1 0 1

Problem - 3: Array Operations:

In [4]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);
add=np.add(x,y)
print("Addition: \n",add)
sub=np.subtract(x,y)
print("Subtraction: \n",sub)
square=np.square(x)#it only takes one argument
print("Square of x: \n", square)
square1=np.square(v)
print("Square of v: \n",square1)
product1=np.dot(v,w)
print("Dot product of v and w: \n",product1)
product2=np.dot(x,y)
print("Dot product of x and y: \n",product2)
concatenate=np.concatenate((x,y))
print("Concatenation: \n",concatenate)
concatenate1=np.vstack((v,w))#it prints in a vertical line
print("Vertical_stacking: \n",concatenate1)
# concatenate2=np.concatenate((x,v))
# print("Concatenation: \n",concatenate2)
#ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has
# 2 dimension(s) and the array at index 1 has 1 dimension(s)




Addition: 
 [[ 6  8]
 [10 13]]
Subtraction: 
 [[-4 -4]
 [-4 -3]]
Square of x: 
 [[ 1  4]
 [ 9 25]]
Square of v: 
 [ 81 100]
Dot product of v and w: 
 219
Dot product of x and y: 
 [[19 22]
 [50 58]]
Concatenation: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Vertical_stacking: 
 [[ 9 10]
 [11 12]]


Problem - 4: Matrix Operations:

In [5]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
inverse=np.linalg.inv(A)#calculate the inverse of mtrix A
# print("Inverse of A: \n",inverse)
dotproduct=np.dot(A,inverse)
print(dotproduct)

c=np.dot(A,B)
print("AB: \n",c)
d=np.dot(B,A)
print("BA: \n",d)
print("Hence AB doesnt equal BA")

e=np.dot(A,B)
transpose1=np.transpose((e))
print("(AB)^t: \n",transpose1)

transpose2=np.transpose((A))
transpose3=np.transpose((B))
f=np.dot(transpose3,transpose2)
print("B^t.A^t: \n", f)
print("Hence prove (AB)^t = B^tA^t.")

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB: 
 [[23 13]
 [51 29]]
BA: 
 [[36 44]
 [13 16]]
Hence AB doesnt equal BA
(AB)^t: 
 [[23 51]
 [13 29]]
B^t.A^t: 
 [[23 51]
 [13 29]]
Hence prove (AB)^t = B^tA^t.


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1 x − y + 2z = −3 3x + y − z = 9

In [11]:
a=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
b=np.array([-1,-3,9])
A=np.linalg.inv(a)
B=np.linalg.solve(A,b)
# Define x, y, and z as numpy arrays or lists before assigning values to their elements.
x = np.zeros(1)  # Initialize x as a NumPy array with 3 elements, all initialized to 0
y = np.zeros(2)  # Initialize y as a NumPy array with 3 elements, all initialized to 0
z = np.zeros(3)  # Initialize z as a NumPy array with 3 elements, all initialized to 0
# Now you can assign values to the elements of x, y, and z
x[0] = B[0]
y[1] = B[1]
z[2] = B[2]
print(x,y,z)

[16.] [ 0. 20.] [  0.   0. -15.]


In [7]:
# 4.2 Experiment: How Fast is Numpy?
# In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays.
#Follow the instructions:

import time

import numpy as np

# 1. Element-wise Addition:
print("1. Element-wise Addition")

# Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds\n")

1. Element-wise Addition
Time taken by Python Lists: 0.21753 seconds
Time taken by numpy: 0.00470 seconds



In [8]:
# 2. Element-wise Multiplication
print("2. Element-wise Multiplication")

# Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds\n")

2. Element-wise Multiplication
Time taken by Python Lists: 0.15989 seconds
Time taken by numpy: 0.00547 seconds



In [9]:
# 3. Dot Product
print("3. Dot Product")

# Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds\n")

3. Dot Product
Time taken by Python Lists: 0.15232 seconds
Time taken by numpy: 0.00216 seconds



In [10]:
# 4. Matrix Multiplication
print("4. Matrix Multiplication")
size = 100

# Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1 = [[i for i in range(size)] for _ in range(size)]
matrix2 = [[j for j in range(size)] for _ in range(size)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds")

4. Matrix Multiplication
Time taken by Python Lists: 0.11885 seconds
Time taken by numpy: 0.00136 seconds
